env:
  browser: true
  es6: true
extends: 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-uses-react: 1,
  class-methods-use-this: 0,
  jsx-quotes: [2, "prefer-single"],
  no-mixed-spaces-and-tabs: 2,
  no-console: 2,
  no-constant-condition: 2,
  no-debugger: 2,
  no-irregular-whitespace: 2,
  no-multi-spaces: 2,
  indent: [2, 2],
}
